// ===================== 线性规划与对偶理论 =====================
const linearProgrammingData = {
    nodes: [
        // 根节点
        { id: "root_linear", label: "📌 线性规划与对偶理论"},
        // ========== 1. 线性规划基本理论 ==========
        { id: "lp_basic_theory", label: "线性规划基本理论" },
        { id: "three_elements", label: "数学模型的三要素", explanation: "决策变量、目标函数、约束条件。" },
        { id: "decision_variable", label: "决策变量", explanation: "问题需要做出的决策，通常为非负实数。" },
        { id: "objective_function", label: "目标函数", explanation: "要最大化或最小化的线性表达式。" },
        { id: "constraints", label: "约束条件", explanation: "问题所受到的限制，由线性等式或不等式组成。" },
        { id: "linearity", label: "线性的含义" },
        { id: "additivity", label: "可加性", explanation: "总效果等于各部分效果之和。" },
        { id: "proportionality", label: "成比例性", explanation: "变量与效果成正比。" },
        { id: "general_standard", label: "线性规划的一般形与标准形" },
        { id: "general_form", label: "一般形", explanation: "目标函数可最大或最小，约束可为等式或不等式，决策变量可非负、非正或无限制。" },
        { id: "standard_form", label: "标准形", explanation: "目标函数最大化，约束为等式，右端项非负，所有决策变量非负。" },
        { id: "general_to_standard", label: "一般形转化为标准形", explanation: "最小化目标乘以 -1；不等式约束引入松弛变量（≤）或剩余变量（≥）；变量无限制则分解为两个非负变量差；右端项负数时乘以 -1 并改变不等号方向。" },
        { id: "lp_concepts", label: "线性规划相关概念" },
        { id: "feasible_solution", label: "可行解", explanation: "满足所有约束条件的解。全体可行解构成可行域。" },
        { id: "optimal_solution", label: "最优解", explanation: "使目标函数达到最优的可行解。" },
        { id: "basis", label: "基", explanation: "设技术矩阵 A 行满秩 (rank(A)=m)，取 m 个线性无关的列向量构成的矩阵 B 称为基矩阵。对应的变量称为基变量。" },
        { id: "basic_solution", label: "基本解", explanation: "令非基变量为 0 后，由基变量确定的解。" },
        { id: "basic_feasible_solution", label: "基可行解", explanation: "满足非负条件的基本解。" },
        { id: "basic_optimal_solution", label: "基最优解", explanation: "使目标函数最优的基可行解。" },
        { id: "degenerate_solution", label: "退化基可行解", explanation: "至少有 1 个基变量取值为 0 的基可行解。" },
        { id: "lp_fundamental_theorem", label: "线性规划基本定理" },
        { id: "convex_set", label: "凸集", explanation: "集合 C 称为凸集，若对任意 \\(x,y\\in C\\) 及 \\(t\\in[0,1]\\)，有 \\((1-t)x + t y \\in C\\)." },
        { id: "extreme_point", label: "顶点（极点）", explanation: "点 x 不能表示为 C 中另外两点的凸组合，则称 x 为 C 的顶点。" },
        { id: "feasible_region_convex", label: "可行域是凸集", explanation: "线性规划问题的可行域是凸集。" },
        { id: "basic_vertex", label: "基可行解 ↔ 顶点", explanation: "基可行解与可行域的顶点一一对应。" },
        { id: "optimal_at_vertex", label: "最优解必在顶点达到", explanation: "若线性规划有最优解，则至少有一个基可行解（顶点）是最优解。" },
        // ========== 2. 单纯形法 ==========
        { id: "simplex_method", label: "单纯形法", explanation: "从可行域的一个顶点出发，沿着可行域的边界移动到使目标函数更优的相邻顶点，直到达到最优。" },
        { id: "initial_basic", label: "初始基可行解的确定", explanation: "寻找单位矩阵作为初始基。若原约束不含单位矩阵，则通过添加松弛变量（≤）或剩余变量（≥）来构造。对于 ≥ 约束或等式，需引入人工变量。" },
        { id: "big_m_method", label: "大M法", explanation: "给人工变量赋予绝对值很大的负系数（最大化问题）或正系数（最小化问题），记为 -M 或 +M。求解时若最优解中人工变量仍为正，则原问题无可行解。" },
        { id: "two_phase_method", label: "两阶段法", explanation: "第一阶段：构造辅助问题，最小化人工变量之和，判断原问题是否可行。若最优值为 0，则进入第二阶段，去除人工变量列，用原目标函数继续求解。" },
        { id: "optimality_condition", label: "最优性判定", explanation: "对于最大化问题，计算所有非基变量的检验数 \\(\\sigma_j = c_j - C_B^T B^{-1} P_j\\)。若所有 \\(\\sigma_j \\le 0\\)，则当前基可行解为最优解。" },
        { id: "reduced_cost", label: "检验数", explanation: "\\(\\sigma_j = c_j - z_j\\)，表示非基变量增加单位时目标函数的变化量。" },
        { id: "entering_variable", label: "进基变量的选择", explanation: "最大化问题选择检验数最大的正检验数对应的非基变量进基；最小化问题选择最小的负检验数对应的非基变量进基。" },
        { id: "leaving_variable", label: "出基变量的选择（最小比值法则）", explanation: "设进基变量为 \\(x_k\\)，计算 \\(\\theta = \\min\\{ b_i / a_{ik} \\mid a_{ik} > 0 \\}\\)，其中 \\(b_i\\) 是当前基变量取值。最小比值对应的基变量出基。若所有 \\(a_{ik} \\le 0\\)，则问题无界。" },
        { id: "pivot_operation", label: "基变换（旋转运算）", explanation: "通过初等行变换将进基变量列变为单位向量，并将出基变量所在行的主元化为 1。" },
        { id: "degeneracy", label: "退化与循环", explanation: "退化指基可行解中存在基变量为零。可能出现循环（迭代不改善目标函数）。Bland 法则可避免循环：进基变量选下标最小的正检验数（最大化），出基变量选取最小比值中下标最小的。" },
        { id: "solution_cases", label: "解的情况判断", explanation: "①所有检验数非正（最大化）且非基变量检验数严格负 → 唯一最优解。②存在非基变量检验数为零 → 无穷多最优解。③存在正检验数且对应列所有系数 ≤ 0 → 无界解。④大M法或两阶段法最优值不为零 → 无可行解。" },
        { id: "simplex_tableau", label: "单纯形表", explanation: "表格形式记录当前基、目标系数、约束系数和右端项，便于迭代计算。" },
        // ========== 3. 对偶理论 ==========
        { id: "dual_theory", label: "对偶理论" },
        { id: "dual_problem", label: "对偶问题的定义", explanation: "每个线性规划问题都有一个对偶问题。对称形式下，原问题：\\(\\max c^T x\\) s.t. \\(Ax \\le b, x \\ge 0\\)；对偶问题：\\(\\min b^T y\\) s.t. \\(A^T y \\ge c, y \\ge 0\\)。" },
        { id: "symmetric_dual", label: "对称形式", explanation: "原问题与对偶问题均采用规范形式：原问题为 max，约束为 ≤，变量非负；对偶问题为 min，约束为 ≥，变量非负。" },
        { id: "nonsymmetric_dual", label: "非对称形式的对偶变换规则", explanation: "原问题约束为等式时，对应对偶变量无约束；原问题变量无约束时，对应约束为等式。具体规则：原问题 max → 对偶 min；约束 ≤ 对应 \\(y_i \\ge 0\\)；约束 = 对应 \\(y_i\\) 无约束；变量 \\(x_j \\ge 0\\) 对应约束 ≥；变量 \\(x_j\\) 无约束对应约束 =。" },
        { id: "weak_duality", label: "弱对偶定理", explanation: "设 x 和 y 分别是原问题和对偶问题的可行解，则 \\(c^T x \\le b^T y\\)（原问题 max）。推论：原问题的任一可行解目标值不超过对偶问题任一可行解目标值。" },
        { id: "strong_duality", label: "强对偶定理", explanation: "若原问题有最优解，则对偶问题也有最优解，且最优目标值相等。" },
        { id: "optimality_dual", label: "最优性定理", explanation: "若 x 和 y 分别是原问题和对偶问题的可行解，且 \\(c^T x = b^T y\\)，则 x 和 y 分别是原问题和对偶问题的最优解。" },
        { id: "complementary_slackness", label: "互补松弛定理", explanation: "设 x 和 y 分别是原问题和对偶问题的最优解，则：对每个约束 i，有 \\(y_i (b_i - A_i x) = 0\\)；对每个变量 j，有 \\(x_j (c_j - A^T_j y) = 0\\)。即若某个约束是松的（非等式），则对应的对偶变量为 0；若对偶变量为正，则对应约束必为等式。" },
        { id: "dual_geometric", label: "对偶的几何解释", explanation: "对偶变量 y 可视为约束右端项 b 的影子价格。" },
        // ========== 4. 对偶单纯形法 =========
        { id: "dual_simplex_method", label: "对偶单纯形法", explanation: "从对偶可行的基本解（所有检验数满足最优性条件）出发，逐步调整使原问题可行（即右端项非负）。适用于某些原问题可行但最优性难满足的情形，如添加新约束。" },
        { id: "dual_simplex_steps", label: "对偶单纯形法步骤", explanation: "Step 1: 建立初始单纯形表，要求所有检验数非正（最大化）或非负（最小化）。Step 2: 检查右端项是否全部非负，若是则已得最优解。否则选右端项最小的负值对应的基变量出基。Step 3: 在所有负系数 \\(a_{rj}\\) 中，选取使 \\(|\\text{检验数} / a_{rj}|\\) 最小的非基变量进基。若某负行无负系数，则原问题无可行解。Step 4: 进行旋转变换，重复 Step 2。" },
        { id: "dual_enter_rule", label: "对偶单纯形法进基规则", explanation: "设出基行 r，对最大化问题，进基变量选择满足 \\(a_{rj} < 0\\) 且比值 \\(|\\sigma_j / a_{rj}|\\) 最小的非基变量 j。对最小化问题，选择 \\(a_{rj} > 0\\) 且比值 \\(|\\sigma_j / a_{rj}|\\) 最小的非基变量。" },
        { id: "dual_compare", label: "单纯形法与对偶单纯形法对比", explanation: "单纯形法保持原可行（右端项非负），改进检验数；对偶单纯形法保持对偶可行（检验数满足最优性），改进原可行。" },
        // ========== 5. 灵敏度分析 ==========
        { id: "sensitivity_analysis", label: "灵敏度分析", explanation: "研究参数变化对最优解和最优值的影响。" },
        { id: "rhs_sensitivity", label: "右端项的变化", explanation: "改变右端项 \\(b \\to b+\\Delta b\\)。当前最优基保持不变的条件为 \\(B^{-1}(b+\\Delta b) \\ge 0\\)。解此不等式可得 Δb 的范围。若超出范围，则用对偶单纯形法求新最优解。" },
        { id: "cost_sensitivity", label: "价值系数的变化（非基变量）", explanation: "若 \\(c_j\\) 是非基变量系数，仅改变该变量的检验数 \\(\\sigma_j\\)。保持最优基不变的条件是 \\(\\sigma_j' \\le 0\\)（最大化），解不等式求出 \\(c_j\\) 的变化范围。" },
        { id: "cost_sensitivity_basic", label: "价值系数的变化（基变量）", explanation: "若 \\(c_j\\) 是基变量系数，会影响所有非基变量检验数。需重新计算检验数并解不等式组，得出保持基不变的 \\(c_j\\) 范围。" },
        { id: "new_variable", label: "新增决策变量", explanation: "已知新变量 \\(x_{n+1}\\) 对应的列 \\(P_{n+1}\\) 和系数 \\(c_{n+1}\\)。计算其在当前基下的表达式：\\(\\theta = B^{-1} P_{n+1}\\)，检验数 \\(\\sigma = c_{n+1} - C_B^T \\theta\\)。若 σ 满足最优条件，则保持最优；否则进基继续迭代。" },
        { id: "new_constraint", label: "新增约束条件", explanation: "若原最优解满足新约束，则仍为最优；否则将新约束加入最优单纯形表（需将基变量用非基变量表示），然后使用对偶单纯形法求解。" },
        { id: "technique_coefficient", label: "技术系数的变化", explanation: "若 \\(a_{ij}\\) 发生变化且对应的变量 \\(x_j\\) 为非基变量，仅影响该列的系数和检验数，重新判断即可。若 \\(x_j\\) 为基变量，则基矩阵 B 改变，通常需要重新求解或修正。" }
    ],
    edges: [
        { from: "root_linear", to: "lp_basic_theory" },
        { from: "root_linear", to: "simplex_method" },
        { from: "root_linear", to: "dual_theory" },
        { from: "root_linear", to: "dual_simplex_method" },
        { from: "root_linear", to: "sensitivity_analysis" },
        { from: "lp_basic_theory", to: "three_elements" },
        { from: "three_elements", to: "decision_variable" },
        { from: "three_elements", to: "objective_function" },
        { from: "three_elements", to: "constraints" },
        { from: "lp_basic_theory", to: "linearity" },
        { from: "linearity", to: "additivity" },
        { from: "linearity", to: "proportionality" },
        { from: "lp_basic_theory", to: "general_standard" },
        { from: "general_standard", to: "general_form" },
        { from: "general_standard", to: "standard_form" },
        { from: "general_standard", to: "general_to_standard" },
        { from: "lp_basic_theory", to: "lp_concepts" },
        { from: "lp_concepts", to: "feasible_solution" },
        { from: "lp_concepts", to: "optimal_solution" },
        { from: "lp_concepts", to: "basis" },
        { from: "lp_concepts", to: "basic_solution" },
        { from: "lp_concepts", to: "basic_feasible_solution" },
        { from: "lp_concepts", to: "basic_optimal_solution" },
        { from: "lp_concepts", to: "degenerate_solution" },
        { from: "lp_basic_theory", to: "lp_fundamental_theorem" },
        { from: "lp_fundamental_theorem", to: "convex_set" },
        { from: "lp_fundamental_theorem", to: "extreme_point" },
        { from: "lp_fundamental_theorem", to: "feasible_region_convex" },
        { from: "lp_fundamental_theorem", to: "basic_vertex" },
        { from: "lp_fundamental_theorem", to: "optimal_at_vertex" },
        { from: "simplex_method", to: "initial_basic" },
        { from: "initial_basic", to: "big_m_method" },
        { from: "initial_basic", to: "two_phase_method" },
        { from: "simplex_method", to: "optimality_condition" },
        { from: "optimality_condition", to: "reduced_cost" },
        { from: "simplex_method", to: "entering_variable" },
        { from: "simplex_method", to: "leaving_variable" },
        { from: "simplex_method", to: "pivot_operation" },
        { from: "simplex_method", to: "degeneracy" },
        { from: "simplex_method", to: "solution_cases" },
        { from: "simplex_method", to: "simplex_tableau" },
        { from: "dual_theory", to: "dual_problem" },
        { from: "dual_problem", to: "symmetric_dual" },
        { from: "dual_problem", to: "nonsymmetric_dual" },
        { from: "dual_theory", to: "weak_duality" },
        { from: "dual_theory", to: "strong_duality" },
        { from: "dual_theory", to: "optimality_dual" },
        { from: "dual_theory", to: "complementary_slackness" },
        { from: "dual_theory", to: "dual_geometric" },
        { from: "dual_simplex_method", to: "dual_simplex_steps" },
        { from: "dual_simplex_method", to: "dual_enter_rule" },
        { from: "dual_simplex_method", to: "dual_compare" },
        { from: "sensitivity_analysis", to: "rhs_sensitivity" },
        { from: "sensitivity_analysis", to: "cost_sensitivity" },
        { from: "sensitivity_analysis", to: "cost_sensitivity_basic" },
        { from: "sensitivity_analysis", to: "new_variable" },
        { from: "sensitivity_analysis", to: "new_constraint" },
        { from: "sensitivity_analysis", to: "technique_coefficient" }
    ]
};

// ===================== 运输问题 =====================
const transportProblemData = {
    nodes: [
        { id: "root_transport", label: "🚚 运输问题"},
        { id: "tp_forms", label: "运输问题的一般形式" },
        { id: "tp_balanced", label: "供需平衡", explanation: "总供应等于总需求。模型：\n\\[ \\min \\sum_{i=1}^{n} \\sum_{j=1}^{m} c_{ij} x_{ij} \\]\n\\[ \\text{s.t. } \\begin{cases} \\sum_{j=1}^{m} x_{ij} = a_i, & \\forall i \\\\ \\sum_{i=1}^{n} x_{ij} = b_j, & \\forall j \\\\ x_{ij} \\ge 0, & \\forall i,j \\end{cases} \\]" },
        { id: "tp_supply_gt", label: "供大于求", explanation: "总供应 > 总需求。产地约束为≤，销地约束为＝。虚设一个销地（运费为0）吸收过剩产量，转化为平衡问题。\n\\[ \\min \\sum_{i=1}^{n} \\sum_{j=1}^{m} c_{ij} x_{ij} \\]\n\\[ \\text{s.t. } \\begin{cases} \\sum_{j=1}^{m} x_{ij} \\le a_i, & \\forall i \\\\ \\sum_{i=1}^{n} x_{ij} = b_j, & \\forall j \\\\ x_{ij} \\ge 0, & \\forall i,j \\end{cases} \\]" },
        { id: "tp_demand_gt", label: "供不应求", explanation: "总需求 > 总供应。销地约束为≤，产地约束为＝。虚设一个产地（运费为0）补足短缺，转化为平衡问题。\n\\[ \\min \\sum_{i=1}^{n} \\sum_{j=1}^{m} c_{ij} x_{ij} \\]\n\\[ \\text{s.t. } \\begin{cases} \\sum_{j=1}^{m} x_{ij} = a_i, & \\forall i \\\\ \\sum_{i=1}^{n} x_{ij} \\le b_j, & \\forall j \\\\ x_{ij} \\ge 0, & \\forall i,j \\end{cases} \\]" },
        { id: "tp_properties", label: "运输问题的性质", explanation: "①技术矩阵元素全为0/1，每列最多两个1（网络矩阵），秩为\\(m+n-1\\)，因此基变量个数为\\(m+n-1\\)。②约束矩阵是全幺模的，故当\\(a_i,b_j\\)为整数时，所有基可行解（包括最优解）自动为整数。③一定有最优解。" },
        { id: "tp_total_unimodular", label: "全幺模性与整数解", explanation: "运输问题的约束矩阵是全幺模矩阵（所有子式行列式为0,±1），因此只要供应量和需求量均为整数，所有基可行解（包括最优解）必为整数，无需引入整数约束。" },
        { id: "tp_dual", label: "对偶问题（位势）", explanation: "产销平衡时的对偶：\n\\[ \\max \\sum_{i=1}^{m} a_i u_i + \\sum_{j=1}^{n} b_j v_j \\]\n\\[ \\text{s.t. } u_i + v_j \\le c_{ij}, \\quad \\forall i,j \\]\n\\(u_i,v_j\\)无约束。经济含义：\\(u_i\\)为产地i的单位货物机会成本，\\(v_j\\)为销地j的单位货物边际节省。" },
        { id: "tp_closed_loop", label: "闭回路", explanation: "由不同行不同列的变量组成的环：\\(x_{i_1j_1}, x_{i_1j_2}, x_{i_2j_2}, x_{i_2j_3}, \\dots, x_{i_kj_1}\\)，每步水平或垂直移动。性质：①含闭回路的变量组线性相关；②变量组线性无关的充要条件是不含闭回路。基变量组中不能出现闭回路。" },
        { id: "tp_tableau", label: "表上作业法（运输单纯形法）" },
        { id: "tp_initial", label: "Step1 初始基可行解" },
        { id: "tp_nw_corner", label: "西北角法", explanation: "从表左上角格子开始分配，依次满足行和列需求。简单快速，但完全不考虑运价，初始解质量较差。" },
        { id: "tp_min_cost", label: "最小元素法", explanation: "从运价最小的格子开始，优先满足该线路。通常比西北角法更优，但仍可能不是最优。" },
        { id: "tp_vogel", label: "Vogel近似法（差值法）", explanation: "计算每行每列次小运价与最小运价之差（罚数），选择罚数最大的行或列中的最小运价格子分配。一般能得到更接近最优的初始解。" },
        { id: "tp_optimality", label: "Step2 最优性检验" },
        { id: "tp_closed_loop_test", label: "闭回路法", explanation: "对每个非基变量（空格）寻找唯一的以基变量为顶点的闭回路，沿回路给单位运量（+1,-1交替），计算目标函数变化量即为检验数。若所有检验数≥0，则当前解最优。" },
        { id: "tp_potential", label: "位势法（对偶变量法）", explanation: "设基变量满足\\(u_i+v_j=c_{ij}\\)。因对偶变量可平移，通常令\\(u_1=0\\)，解出所有\\(u_i,v_j\\)。非基变量检验数\\(\\sigma_{ij}=c_{ij}-(u_i+v_j)\\)。若所有\\(\\sigma_{ij}\\ge0\\)，则最优。" },
        { id: "tp_improve", label: "Step3 改进运输方案", explanation: "选检验数最负的非基变量进基，找出其闭回路，令\\(\\theta=\\min\\){偶数顶点运量}，奇数顶点加\\(\\theta\\)，偶数顶点减\\(\\theta\\)。得到新基可行解，重复检验。" },
        { id: "tp_degenerate", label: "退化及处理", explanation: "退化情况：①初始解中同时满足一行一列时，需在划去的行/列中任意选一个空格填0作为基变量，保持基变量数为\\(m+n-1\\)。②调整时多个偶数顶点同时减到0，只让其中一个离基，其余保留为0（仍视为基变量）。" },
        { id: "tp_multiple", label: "无穷多最优解", explanation: "当某个非基变量检验数=0时，将其进基调整可得另一个最优解，表明有无穷多最优解。" },
        { id: "tp_special", label: "特殊运输问题" },
        { id: "tp_flexible_demand", label: "需求可变的运输问题", explanation: "将需求地拆为刚性需求（必须满足）和柔性需求（可不满足）。总供给介于最小总需求和最大总需求之间时，虚设产地。刚性需求不能从虚拟产地进货，对应运价设为M（大正数）；柔性需求运价为0。" },
        { id: "tp_transshipment", label: "转运问题", explanation: "允许中间点转运，每个节点既可发也可收。通用解法：设总产量Q（足够大），每个节点自身到自身的变量\\(x_{ii}=Q-t_i\\)，将转运成本纳入目标，转化为平衡运输问题。若转运需收费，可拆分节点处理。" },
        { id: "tp_maximize", label: "最大化目标函数", explanation: "方法1：目标函数取负，改为最小化，直接用表上作业法。方法2：令\\(c'_{ij}=M-c_{ij}\\)（M为最大运价），求\\(\\min \\sum c'_{ij}x_{ij}\\)。" }
    ],
    edges: [
        { from: "root_transport", to: "tp_forms" },
        { from: "root_transport", to: "tp_properties" },
        { from: "root_transport", to: "tp_dual" },
        { from: "root_transport", to: "tp_closed_loop" },
        { from: "root_transport", to: "tp_tableau" },
        { from: "root_transport", to: "tp_special" },
        { from: "root_transport", to: "tp_total_unimodular" },
        { from: "tp_forms", to: "tp_balanced" },
        { from: "tp_forms", to: "tp_supply_gt" },
        { from: "tp_forms", to: "tp_demand_gt" },
        { from: "tp_tableau", to: "tp_initial" },
        { from: "tp_tableau", to: "tp_optimality" },
        { from: "tp_tableau", to: "tp_improve" },
        { from: "tp_tableau", to: "tp_degenerate" },
        { from: "tp_tableau", to: "tp_multiple" },
        { from: "tp_initial", to: "tp_nw_corner" },
        { from: "tp_initial", to: "tp_min_cost" },
        { from: "tp_initial", to: "tp_vogel" },
        { from: "tp_optimality", to: "tp_closed_loop_test" },
        { from: "tp_optimality", to: "tp_potential" },
        { from: "tp_special", to: "tp_flexible_demand" },
        { from: "tp_special", to: "tp_transshipment" },
        { from: "tp_special", to: "tp_maximize" }
    ]
};

// ===================== 整数规划 =====================
const integerProgrammingData = {
    nodes: [
        { id: "root_integer", label: "🧩 整数规划"},
        { id: "int_cutting_plane", label: "割平面法", explanation: "先求解松弛线性规划，再不断增加割平面约束（即切割不等式），逐步切除不包含整数可行解的部分，最终使最优解落在整数极点上。适用于纯整数规划。" },
        { id: "cp_step1", label: "割平面法 Step 1", explanation: "求解原整数规划对应的松弛线性规划（去掉整数约束），得到最优单纯形表。" },
        { id: "cp_step2", label: "割平面法 Step 2", explanation: "检查最优解是否全为整数。若是，停止；否则转 Step 3。" },
        { id: "cp_step3", label: "割平面法 Step 3", explanation: "任选一个非整数基变量对应的约束行，生成割平面（Gomory约束）。常用形式：将系数和右端项分解为整数部分+真分数，得到不等式 \\(\\sum_{j} f_{ij} x_j \\ge f_{i0}\\)（其中 \\(f_{ij}\\) 为分数部分）。将该约束加入原表中，用对偶单纯形法继续求解。" },
        { id: "cp_gomory", label: "Gomory 割平面生成细节", explanation: "对于基变量 \\(x_{B_i} = \\sum_{j \\in N} a_{ij} x_j + a_{i0}\\)，记 \\(a_{ij} = [a_{ij}] + f_{ij}\\)，\\(a_{i0} = [a_{i0}] + f_{i0}\\)，其中 \\(0 \\le f_{ij} < 1\\)，\\(0 < f_{i0} < 1\\)。Gomory 约束为 \\(\\sum_{j \\in N} (-f_{ij}) x_j \\le -f_{i0}\\)，等价于 \\(\\sum_{j \\in N} f_{ij} x_j \\ge f_{i0}\\)。经验上优先选择分数部分 \\(f_{i0}\\) 最大的行生成割平面。" },
        { id: "int_branch_bound", label: "分支定界法", explanation: "通过松弛解的分支和定界剪枝，系统地搜索整数可行解。适用于纯整数和混合整数规划。" },
        { id: "bb_step1", label: "分支定界 Step 1 (松弛)", explanation: "求解原整数规划对应的松弛线性规划，得到最优值 \\(z^*\\)。若为整数解则停止；否则记录上界 \\(UB = z^*\\)，下界 \\(LB = -\\infty\\)（最大化问题）。" },
        { id: "bb_step2", label: "分支定界 Step 2 (分支)", explanation: "选择一个不满足整数约束的变量 \\(x_k = \\beta\\)（\\(\\beta\\) 非整数），分支为两个子问题：\\(x_k \\le \\lfloor \\beta \\rfloor\\) 和 \\(x_k \\ge \\lceil \\beta \\rceil\\)，分别求解。" },
        { id: "bb_step3", label: "分支定界 Step 3 (定界)", explanation: "在各分支中，若有整数可行解，更新下界 \\(LB = \\max(LB, z_{int})\\)；若某分支的松弛解 \\(z \\le LB\\)（或 \\(z\\) 无可行解），则剪去该分支。否则继续分支。" },
        { id: "bb_step4", label: "分支定界 Step 4 (迭代)", explanation: "重复分支和定界，直至所有分支被剪去或达到精度要求，此时下界对应的解即为最优整数解。" },
        { id: "int_implicit_enum", label: "隐枚举法", explanation: "针对0-1整数规划的一种特殊分支定界法，利用变量只能取0或1的特性进行分支和剪枝。通常按目标函数系数排序变量，并利用约束条件提前判定不可行分支，避免完全枚举。" },
        { id: "int_assignment", label: "指派问题", explanation: "指派问题是特殊的0-1整数规划，将 n 个任务分配给 n 个人，每人一任务，使总成本最小。模型为：\n\\[ \\min \\sum_{i=1}^n \\sum_{j=1}^n c_{ij} x_{ij},\\quad \\text{s.t.}\\ \\sum_{j=1}^n x_{ij}=1,\\ \\sum_{i=1}^n x_{ij}=1,\\ x_{ij}\\in\\{0,1\\} \\] 可视为运输问题（\\(m=n\\)，供需为1的特例），但基变量数为 \\(2n-1\\)，且有 n 个基变量为1，会出现严重退化，故采用匈牙利法求解。" },
        { id: "as_hungarian", label: "匈牙利法", explanation: "利用性质：价格矩阵行或列加减常数不影响最优解。通过变换矩阵产生更多零元素，然后寻找独立零元素进行指派。" },
        { id: "as_step1", label: "匈牙利法 Step 1 (矩阵变换)", explanation: "每行减去该行最小元素；每列减去该列最小元素。使得每行每列至少有一个零。" },
        { id: "as_step2", label: "匈牙利法 Step 2 (试指派)", explanation: "尝试用最少的独立零元素覆盖所有零。\n常用方法：① 从只有一个零的行（列）开始，给该零加圈记为 ⓪，并划掉同行同列的其他零（标记为 Ø）；② 重复至所有零被处理；③ 若 ⓪ 的个数 = n，则最优解已找到；若 ⓪ 的个数 < n，转 Step 3。" },
        { id: "as_step3", label: "匈牙利法 Step 3 (画最少直线)", explanation: "用最少的直线（横线或竖线）覆盖所有零元素。\n步骤：① 对没有 ⓪ 的行打 √；② 对 √ 行中含 Ø 的列打 √；③ 对 √ 列中含 ⓪ 的行打 √；重复②③；④ 对没有 √ 的行画横线，对有 √ 的列画竖线。直线数若 < n，转 Step 4；若 = n，则 Step 2 有误需重新指派。" },
        { id: "as_step4", label: "匈牙利法 Step 4 (矩阵调整)", explanation: "找出未被直线（横线/竖线）覆盖的最小元素 \\(\\theta\\)。所有未被直线覆盖的行减去 \\(\\theta\\)，所有被直线覆盖的列加上 \\(\\theta\\)。得到新矩阵，\n之前标记的 ⓪ 和 Ø 全部清除，返回 Step 2 重新试指派。" },
        { id: "as_duality", label: "匈牙利法解的唯一性说明", explanation: "当圈数 < n 时，可能存在多个独立零组合，解法不唯一，但最优目标值相同。若 Step 2 中出现多个可选零，可任选，最终都能得到最优解。" }
    ],
    edges: [
        { from: "root_integer", to: "int_cutting_plane" },
        { from: "int_cutting_plane", to: "cp_step1" },
        { from: "int_cutting_plane", to: "cp_step2" },
        { from: "int_cutting_plane", to: "cp_step3" },
        { from: "int_cutting_plane", to: "cp_gomory" },
        { from: "root_integer", to: "int_branch_bound" },
        { from: "int_branch_bound", to: "bb_step1" },
        { from: "int_branch_bound", to: "bb_step2" },
        { from: "int_branch_bound", to: "bb_step3" },
        { from: "int_branch_bound", to: "bb_step4" },
        { from: "root_integer", to: "int_implicit_enum" },
        { from: "root_integer", to: "int_assignment" },
        { from: "int_assignment", to: "as_hungarian" },
        { from: "as_hungarian", to: "as_step1" },
        { from: "as_hungarian", to: "as_step2" },
        { from: "as_hungarian", to: "as_step3" },
        { from: "as_hungarian", to: "as_step4" },
        { from: "as_hungarian", to: "as_duality" }
    ]
};

// ===================== 非线性规划 =====================
const nonlinearProgrammingData = {
    nodes: [
        { id: "root_nonlinear", label: "📈 非线性规划", explanation: "目标函数或约束条件至少有一个是非线性函数的优化问题。分为无约束优化和约束优化。本节点包含凸函数/凸规划理论、无约束优化的精确线搜索方法（黄金分割、斐波那契、牛顿法、插值法）、梯度下降法与牛顿法（含收敛性分析）、约束优化的KKT条件（含约束规格、互补松弛、几何意义）、外点罚函数法、内点障碍函数法、增广拉格朗日乘子法。所有内容均提供数学推导、算法步骤、优缺点对比及数值稳定性讨论。" },
        { id: "nlp_form", label: "非线性规划的一般形式", explanation: "标准形式：\n\\[ \\min f(x) \\quad \\text{s.t.} \\begin{cases} g_i(x) \\ge 0, & i=1,\\dots,p \\\\ h_j(x) = 0, & j=1,\\dots,q \\end{cases} \\]\n其中 \\(x \\in \\mathbb{R}^n\\)，\\(f, g_i, h_j\\) 至少有一个是非线性函数。若 \\(p=q=0\\)，则为无约束优化。可行域 \\(\\Omega = \\{x \\mid g_i(x) \\ge 0, h_j(x) = 0\\}\\)。非线性规划的难点：非凸性导致多个局部最优解，梯度消失或奇异性，约束非线性引起的可行域复杂。" },
        { id: "nlp_convex_func", label: "凸函数定义与判别", explanation: "定义：设 \\(\\Omega \\subseteq \\mathbb{R}^n\\) 是非空凸集，\\(f: \\Omega \\to \\mathbb{R}\\)。若对任意 \\(x, y \\in \\Omega\\) 及 \\(\\alpha \\in [0,1]\\)，有 \\(f(\\alpha x + (1-\\alpha)y) \\le \\alpha f(x) + (1-\\alpha) f(y)\\)，则称 \\(f\\) 是凸函数。若严格不等，则严格凸。\n\n一阶条件（可微）：\\(f\\) 在开凸集上可微，则凸当且仅当 \\(f(y) \\ge f(x) + \\nabla f(x)^T (y-x), \\forall x,y\\)。几何解释：切线始终在函数下方。\n\n二阶条件（二阶可微）：\\(f\\) 是凸函数当且仅当它的海森矩阵 \\(\\nabla^2 f(x)\\) 在 \\(\\Omega\\) 上半正定（所有特征值非负）。严格凸要求正定。\n\n常用凸函数：仿射函数、二次函数 \\(x^T Q x\\) 其中 \\(Q \\succeq 0\\)、范数、指数函数、负熵等。\n\n凸性保持运算：非负加权和、与仿射函数复合、逐点取最大值、下确界等。" },
        { id: "nlp_convex_prog", label: "凸规划", explanation: "定义：\\(\\min f(x)\\)，s.t. \\(g_i(x) \\ge 0\\)，\\(h_j(x)=0\\)。若 \\(f\\) 是凸函数，\\(g_i\\) 是凹函数（或 \\(-g_i\\) 凸），\\(h_j\\) 是仿射函数，则称为凸规划。此时可行域是凸集。\n\n核心性质：\n1. 任何局部极小点必是全局极小点。\n2. 最优解集是凸集。\n3. 若 \\(f\\) 严格凸，则最优解唯一。\n4. KKT条件是全局最优解的充要条件（在约束规格下）。\n\n凸规划是“易于求解”的问题，因为任何下降方法都不会陷入非全局的局部极小点。" },
        { id: "nlp_unconstrained", label: "无约束优化问题", explanation: "目标：\\(\\min_{x \\in \\mathbb{R}^n} f(x)\\)，假定 \\(f\\) 连续可微。一阶必要条件：若 \\(x^*\\) 是局部极小点，则 \\(\\nabla f(x^*) = 0\\)（驻点）。二阶必要条件：\\(\\nabla^2 f(x^*) \\succeq 0\\)（半正定）。二阶充分条件：\\(\\nabla f(x^*) = 0\\) 且 \\(\\nabla^2 f(x^*) \\succ 0\\)（正定），则 \\(x^*\\) 是严格局部极小点。\n\n无约束优化常用迭代法：\\(x_{k+1} = x_k + \\alpha_k d_k\\)，其中 \\(d_k\\) 是搜索方向，\\(\\alpha_k\\) 是步长。关键是选择方向和步长。" },
        { id: "nlp_descent_iter", label: "下降迭代法基本框架", explanation: "算法步骤：\n1. 初始化：\\(x_0\\)，\\(k=0\\)。\n2. 若 \\(\\|\\nabla f(x_k)\\| \\le \\epsilon\\)，停机。\n3. 选择下降方向 \\(d_k\\) 满足 \\(\\nabla f(x_k)^T d_k < 0\\)。\n4. 线搜索求步长 \\(\\alpha_k > 0\\)，使得 \\(f(x_k + \\alpha_k d_k) < f(x_k)\\) 且满足充分下降条件（如Armijo条件）。\n5. 更新 \\(x_{k+1} = x_k + \\alpha_k d_k\\)，\\(k \\leftarrow k+1\\)，转2。\n\n下降方向：负梯度方向为最速下降；牛顿方向 \\(d_k = -H_k^{-1} g_k\\) 为二阶下降；拟牛顿方向用近似海森。\n\n步长策略：精确线搜索（极小化 \\(\\varphi(\\alpha)\\)）或非精确线搜索（Armijo、Goldstein、Wolfe条件）。非精确搜索保证收敛且计算量小。" },
        { id: "nlp_line_search", label: "一维线搜索", explanation: "给定方向 \\(d_k\\)，定义 \\(\\varphi(\\alpha) = f(x_k + \\alpha d_k)\\)，\\(\\alpha > 0\\)。需要找到 \\(\\alpha_k\\) 使 \\(\\varphi\\) 充分下降。常用方法分为三类：\n- 试探法：黄金分割、斐波那契（不需导数，仅比较函数值）\n- 插值法：二次/三次插值（利用函数值或导数信息）\n- 导数法：牛顿法、割线法（需导数或近似导数）\n\n对于凸函数且单峰时，试探法能可靠缩小区间；对于非凸函数，线搜索可能找到局部极小点或满足Wolfe条件的点即可。" },
        { id: "nlp_golden_section", label: "黄金分割法（0.618法）", explanation: "适用条件：\\(\\varphi(\\alpha)\\) 在初始区间 \\([a,b]\\) 上是单峰函数（只一个极小点）。\n\n原理：每次取两个内点，比较函数值后缩小包围区间，并使新区间长度与原区间长度之比为常数 \\(\\tau = (\\sqrt{5}-1)/2 \\approx 0.618\\)（黄金分割数）。这样可以保证每次只需要计算一个新点，节省函数估值。\n\n算法步骤：\n1. 给定 \\([a,b]\\)，精度 \\(\\varepsilon\\)。\n2. 计算 \\(x_1 = a + (1-\\tau)(b-a)\\)，\\(x_2 = a + \\tau(b-a)\\)，\\(f_1 = \\varphi(x_1)\\)，\\(f_2 = \\varphi(x_2)\\)。\n3. 循环：\n   - 若 \\(b-a < \\varepsilon\\)，输出 \\((a+b)/2\\) 终止。\n   - 若 \\(f_1 < f_2\\)，则置 \\(b = x_2\\)，\\(x_2 = x_1\\)，\\(f_2 = f_1\\)，\\(x_1 = a + (1-\\tau)(b-a)\\)，重新计算 \\(f_1\\)。\n   - 若 \\(f_1 \\ge f_2\\)，则置 \\(a = x_1\\)，\\(x_1 = x_2\\)，\\(f_1 = f_2\\)，\\(x_2 = a + \\tau(b-a)\\)，重新计算 \\(f_2\\)。\n\n收敛性：区间长度以 \\(\\tau^{k-1}\\) 速率缩小，线性收敛。" },
        { id: "nlp_fibonacci", label: "斐波那契法", explanation: "与黄金分割类似，但区间缩短比例不固定，而是使用斐波那契数列 \\(F_0=F_1=1, F_{k}=F_{k-1}+F_{k-2}\\)。最终区间长度为初始长度的 \\(1/F_{n+1}\\)。\n\n算法：预先指定总函数评价次数 \\(n\\)，则初始内点位置由 \\(F_{n-1}/F_{n+1}\\) 和 \\(F_n/F_{n+1}\\) 决定。每次缩小区间后，根据剩余迭代次数重新计算比例。斐波那契法是给定函数评价次数下最优的策略（区间缩放最快）。黄金分割法是斐波那契当 \\(n \\to \\infty\\) 时的极限，实现简单。\n\n区别：黄金分割法不需要预知迭代次数，而斐波那契法需要提前确定 \\(n\\)，但精度更高。" },
        { id: "nlp_newton_1d", label: "一维牛顿法", explanation: "利用泰勒展开逼近 \\(\\varphi'(\\alpha)\\)：\\(\\varphi'(\\alpha) \\approx \\varphi(\\alpha_k) + \\varphi''(\\alpha_k)(\\alpha-\\alpha_k) 。令导数为0得 \\(\\alpha_{k+1} = \\alpha_k - \\frac{\\varphi'(\\alpha_k)}{\\varphi''(\\alpha_k)}\\)。\n\n适用条件：\\(\\varphi\\) 二阶可导，且 \\(\\varphi''(\\alpha_k) > 0\\)（确保极小值）。\n\n收敛速度：如果初值接近极小点，二次收敛。但若二阶导为负或零，可能收敛到最大值或发散。常与线搜索结合（阻尼牛顿法）：\\(\\alpha_{k+1} = \\alpha_k - \\gamma \\frac{\\varphi'(\\alpha_k)}{\\varphi''(\\alpha_k)}\\)，\\(\\gamma\\) 为步长。\n\n评价：仅适用于导数容易计算的情形，且需要二阶导数。" },
        { id: "nlp_interpolation", label: "插值法（多项式逼近）", explanation: "利用 \\(\\varphi(\\alpha)\\) 在若干点上的函数值和/或导数值构造一个低次多项式，求该多项式的最小点作为 \\(\\alpha\\) 的估计。\n\n二次插值：给定三点 \\(\\alpha_1 < \\alpha_2 < \\alpha_3\\)，计算 \\(\\varphi_i\\)，拟合二次函数 \\(p(\\alpha) = a\\alpha^2 + b\\alpha + c\\)。令 \\(p'(\\alpha)=0\\) 得 \\(\\alpha^* = -b/(2a)\\)。然后用新点替换最远点，反复迭代。\n\n三次插值：利用两个端点的函数值和导数值可唯一确定三次多项式，具有二次收敛率。最常用的是基于导数的三次插值，配合 Wolfe 条件实现高效的线搜索（如 MINPACK 中的实现）。\n\n优势：比试探法收敛快（超线性），尤其当 \\(\\varphi\\) 光滑时。现代优化库（如 L-BFGS 的线搜索）通常使用插值法。" },
        { id: "nlp_gradient_descent", label: "梯度下降法", explanation: "方向：\\(d_k = -\\nabla f(x_k)\\)（负梯度）。步长选择：\n- 固定步长（需人为调节，可能不收敛）\n- 精确线搜索：\\(\\alpha_k = \\arg\\min_{\\alpha>0} f(x_k - \\alpha \\nabla f(x_k))\\)\n- 回溯线搜索（Armijo条件）：\\(f(x_k + \\alpha d_k) \\le f(x_k) + c_1 \\alpha \\nabla f(x_k)^T d_k\\)，其中 \\(c_1 \\in (0,1)\\)\n\n收敛性：对于凸光滑函数，梯度下降迭代复杂度为 \\(O(1/\\varepsilon)\\) 达到 \\(\\varepsilon\\) 精度。若函数强凸（\\(\\mu\\) 强凸，\\(L\\) Lipschitz 梯度），线性收敛：\\(\\|x_k - x^*\\|^2 \\le (1 - \\mu/L)^k \\|x_0 - x^*\\|^2\\)。\n\n缺点：条件数大的情形（椭球等高线）收敛极慢，产生“锯齿”现象。" },
        { id: "nlp_newton_md", label: "牛顿法（多维）", explanation: "迭代公式：\\(x_{k+1} = x_k - [\\nabla^2 f(x_k)]^{-1} \\nabla f(x_k)\\)。\n\n推导：在 \\(x_k\\) 处二阶泰勒展开 \\(f(x_k + d) \\approx f(x_k) + g_k^T d + \\frac{1}{2} d^T H_k d\\)，对 \\(d\\) 求导得 \\(H_k d = -g_k\\)，解出 \\(d = -H_k^{-1} g_k\\)。\n\n性质：二次收敛（接近最优解时每迭代精度平方增加），对强凸函数全局收敛（若步长适当）。\n\n问题与改进：\n- 海森矩阵可能非正定，导致方向不下降。修正：加正则项 \\(H_k + \\mu I\\)（Levenberg-Marquardt），或使用信赖域。\n- 计算 \\(H_k\\) 和求解线性系统代价高（\\(O(n^3)\\)）。\n- 拟牛顿法（BFGS）用一阶信息逼近海森逆，保持超线性收敛，工程中更常用。" },
        { id: "nlp_compare", label: "梯度下降 vs 牛顿法对比", explanation: "| 特性 | 梯度下降 | 牛顿法 |\n|------|----------|--------|\n| 收敛速度 | 线性（条件数相关） | 二次（附近） |\n| 每迭代复杂度 | \\(O(n)\\) | \\(O(n^3)\\) |\n| 所需信息 | 一阶导数 | 一阶+二阶导数 |\n| 对非凸问题 | 可能收敛到鞍点 | 易收敛到鞍点（但修正可改善） |\n| 内存 | 低 | 高（存储海森） |\n| 超参数 | 步长策略 | 正则化参数 |\n\n建议：大规模问题用梯度下降或（随机梯度）；中小规模高精度用拟牛顿（BFGS）；非光滑问题需次梯度方法。" },
        { id: "nlp_constrained", label: "约束优化问题概述", explanation: "带有不等式和等式约束的非线性规划。求解策略：\n- 间接法：将约束以惩罚或障碍形式加入目标，转化为无约束（外点、内点、增广拉格朗日）。\n- 直接法：在可行域内产生迭代点（可行方向法、SQP、GRG）。\n理论核心：KKT条件是判断最优解的必要/充分条件。" },
        { id: "nlp_kkt", label: "KKT条件（详细推导与约束规格）", explanation: "考虑问题：\\(\\min f(x)\\)，\\(g_i(x) \\ge 0 (i=1..l)\\)，\\(h_j(x)=0 (j=1..m)\\)。设 \\(x^*\\) 是局部极小点，且约束满足某种约束规格（regularity condition）。则存在乘子 \\(\\mu_i \\ge 0\\) 和 \\(\\lambda_j\\) 使得：\n\n1. 梯度平衡条件（驻点条件）：\n   \\[ \\nabla f(x^*) - \\sum_{i=1}^l \\mu_i \\nabla g_i(x^*) - \\sum_{j=1}^m \\lambda_j \\nabla h_j(x^*) = 0 \\]\n\n2. 互补松弛条件：\\(\\mu_i g_i(x^*) = 0,\\ \\forall i\\)（若 \\(g_i(x^*) > 0\\) 则 \\(\\mu_i=0\\)；若 \\(\\mu_i>0\\) 则 \\(g_i(x^*)=0\\)）\n\n3. 原可行条件：\\(g_i(x^*) \\ge 0,\\ h_j(x^*) = 0\\)\n\n4. 对偶可行条件：\\(\\mu_i \\ge 0\\)\n\n约束规格：最常用的是LICQ（有效约束梯度线性无关）。有效约束集合：\\(I(x^*) = \\{i \\mid g_i(x^*) = 0\\}\\)。LICQ要求 \\(\\{\\nabla g_i(x^*), i \\in I(x^*)\\} \\cup \\{\\nabla h_j(x^*), j=1..m\\}\\) 线性无关。还有其他如MFCQ、Slater条件等。\n\n几何意义：\\(-\\nabla f(x^*)\\) 落在有效约束法线的锥内（因为 \\(\\mu_i \\nabla g_i\\) 指向可行域的“外部”）。\n\n凸规划的充分性：若问题为凸规划（\\(f\\)凸，\\(g_i\\)凹，\\(h_j\\)线性），且 \\(x^*\\) 满足KKT条件，则 \\(x^*\\) 是全局最优解。" },
        { id: "nlp_penalty", label: "外点罚函数法", explanation: "将约束违反量作为惩罚项，构造无约束问题：\n\\[ P(x;\\rho) = f(x) + \\rho \\left( \\sum_{i=1}^l [\\min(0, g_i(x))]^2 + \\sum_{j=1}^m h_j^2(x) \\right) \\]\n其中 \\(\\rho > 0\\) 是罚因子。\n\n算法：\n1. 选择 \\(\\rho_0 > 0\\)（如1），\\(c > 1\\)（如10），初始点 \\(x_0\\)（任意）。\n2. 对 \\(k=0,1,2,\\ldots\\)：\n   - 解无约束问题 \\(\\min P(x;\\rho_k)\\)，得 \\(x_k^*\\)（可用梯度法、牛顿法）。\n   - 若 \\(\\max(\\max_i |\\min(0,g_i(x_k^*))|, \\max_j |h_j(x_k^*)|) \\le \\epsilon\\)，停止。\n   - 否则 \\(\\rho_{k+1} = c \\rho_k\\)。\n\n性质：当 \\(\\rho \\to \\infty\\) 时，\\(x^*(\\rho) \\to x^*\\)（原问题最优解）。但罚函数的海森矩阵条件数随 \\(\\rho\\) 增大而趋于无穷，导致数值病态，难以精确求解。\n\n优点：初始点任意；算法简单。缺点：收敛慢，病态，罚因子需无限增大。" },
        { id: "nlp_barrier", label: "内点障碍函数法", explanation: "要求初始点严格可行（\\(g_i(x_0) > 0\\)）。构造障碍函数：\n\\[ B(x;\\mu) = f(x) - \\mu \\sum_{i=1}^l \\ln(g_i(x)) \\]\n（默认 \\(g_i(x) > 0\\)）。当 \\(x\\) 接近边界时，\\(-\\ln(g_i) \\to +\\infty\\)，形成“障碍”。\n\n算法：\n1. 选择 \\(\\mu_0 > 0\\)（如0.5），\\(\\sigma \\in (0,1)\\)（如0.1），初始可行点 \\(x_0\\)。\n2. 对 \\(k=0,1,2,\\ldots\\)：\n   - 从 \\(x_k\\) 出发解 \\(\\min B(x;\\mu_k)\\) 得 \\(x_{k+1}\\)。\n   - 若 \\(\\mu_k \\le \\epsilon\\) 且约束满足精度，停止。\n   - 否则 \\(\\mu_{k+1} = \\sigma \\mu_k\\)。\n\n性质：当 \\(\\mu \\to 0^+\\) 时，\\(x^*(\\mu) \\to x^*\\)。对数障碍函数的梯度为 \\(\\nabla B = \\nabla f - \\mu \\sum \\frac{1}{g_i} \\nabla g_i\\)，海森矩阵在可行域内是连续的。\n\n优点：迭代点始终可行；无病态问题（\\(\\mu\\) 不会趋近0太快）。缺点：需要严格可行初值；不直接处理等式约束（通常将等式约束作为两个不等式，或预处理消去）。" },
        { id: "nlp_aug_lagrange", label: "增广拉格朗日法（乘子法）", explanation: "结合拉格朗日函数和外点罚函数的优势。以等式约束为例：\n\\[ L_A(x, \\lambda; \\rho) = f(x) + \\sum_{j=1}^m \\lambda_j h_j(x) + \\frac{\\rho}{2} \\sum_{j=1}^m h_j^2(x) \\]\n\n主要定理：存在有限 \\(\\rho_0\\) 使得乘子更新公式在局部收敛（无需 \\(\\rho \\to \\infty\\)）。\n\n算法（等式约束）：\n1. 给定 \\(\\lambda^0\\)（如0），\\(\\rho_0 > 0\\)，\\(c > 1\\)，\\(\\epsilon > 0\\)。\n2. 对 \\(k=0,1,2,\\ldots\\)：\n   - 求解 \\(\\min_x L_A(x, \\lambda^k; \\rho_k)\\)，得 \\(x^k\\)。\n   - 若 \\(\\|h(x^k)\\| \\le \\epsilon\\)，停止。\n   - 更新乘子：\\(\\lambda^{k+1}_j = \\lambda^k_j + \\rho_k h_j(x^k)\\)。\n   - 可选择增大 \\(\\rho_{k+1} = c \\rho_k\\)，但不是必须。\n\n不等式约束处理：引入松弛变量 \\(s_i \\ge 0\\) 将 \\(g_i(x) \\ge 0\\) 写为 \\(g_i(x) - s_i = 0, s_i \\ge 0\\)，并对非负约束用内点法或简单投影。实际中更常用增广拉格朗日+障碍（如 LANCELOT 中的形式）。\n\n优点：有限罚因子即可精确收敛；收敛速度快（超线性）；数值稳定。是现代约束优化软件的首选方法。" }
    ],
    edges: [
        { from: "root_nonlinear", to: "nlp_form" },
        { from: "root_nonlinear", to: "nlp_convex_func" },
        { from: "root_nonlinear", to: "nlp_convex_prog" },
        { from: "root_nonlinear", to: "nlp_unconstrained" },
        { from: "root_nonlinear", to: "nlp_constrained" },
        { from: "nlp_unconstrained", to: "nlp_descent_iter" },
        { from: "nlp_descent_iter", to: "nlp_line_search" },
        { from: "nlp_line_search", to: "nlp_golden_section" },
        { from: "nlp_line_search", to: "nlp_fibonacci" },
        { from: "nlp_line_search", to: "nlp_newton_1d" },
        { from: "nlp_line_search", to: "nlp_interpolation" },
        { from: "nlp_unconstrained", to: "nlp_gradient_descent" },
        { from: "nlp_unconstrained", to: "nlp_newton_md" },
        { from: "nlp_unconstrained", to: "nlp_compare" },
        { from: "nlp_constrained", to: "nlp_kkt" },
        { from: "nlp_constrained", to: "nlp_penalty" },
        { from: "nlp_constrained", to: "nlp_barrier" },
        { from: "nlp_constrained", to: "nlp_aug_lagrange" }
    ]
};

// ===================== 图与网络 =====================
const graphNetworkData = {
    nodes: [
        { id: "root_graph", label: "🌐 图与网络"},
        { id: "graph_def", label: "图的定义", explanation: "图 \\(G = (V, E)\\) 由顶点集 \\(V = \\{v_1, v_2, \\dots, v_n\\}\\) 和边集 \\(E = \\{e_k\\}_{k=1}^m\\) 构成，其中每条边是 \\(V\\) 中有限个元素的无序对（无向边）或有序对（有向弧）。" },
        { id: "graph_types", label: "图的分类", explanation: "根据边的方向性：\n- 无向图：所有边无方向。\n- 有向图：所有边有方向。\n- 混合图：同时包含有向边和无向边。" },
        { id: "vertex_degree", label: "顶点的度", explanation: "顶点 \\(v\\) 的度 \\(d(v)\\) 是关联该顶点的边的数目。有向图中分为入度（指向该顶点的边数）和出度（从该顶点出发的边数）。\n- 奇点：度为奇数的顶点。\n- 偶点：度为偶数的顶点。\n- 孤立点：度为0。\n- 悬挂点：度为1。" },
        { id: "handshaking_lemma", label: "握手定理", explanation: "对于无向图 \\(G=(V,E)\\)，有 \\(\\sum_{v \\in V} d(v) = 2|E|\\)。推论：奇点个数必为偶数。对于有向图，所有顶点的入度之和等于出度之和。" },
        { id: "chain", label: "链", explanation: "链是指一组首尾相连的边的序列，即顶点和边交替的序列，相邻顶点有边相连。链中的边可以重复，但简单链中顶点不重复。" },
        { id: "cycle", label: "圈", explanation: "起点和终点相同的链称为圈（或环）。在无向图中，圈是一个闭合的路径。" },
        { id: "circuit", label: "回路", explanation: "在有向图中，如果圈上所有边的方向一致（均沿着前进方向），则称为回路。" },
        { id: "connectivity", label: "连通性", explanation: "无向图中，若任意两个顶点之间都存在至少一条链，则称该图连通。有向图中，若忽略方向后连通，称为弱连通；若任意两点间存在有向路径，称为强连通。" },
        { id: "subgraph", label: "子图", explanation: "设 \\(G' = (V', E')\\)，若 \\(V' \\subseteq V\\) 且 \\(E' \\subseteq E\\)，则称 \\(G'\\) 是 \\(G\\) 的子图。特别地，若 \\(V' = V\\)（保留所有顶点），则称 \\(G'\\) 为支撑子图（生成子图）。" },
        { id: "tree_def", label: "树的定义", explanation: "树是一种连通且无圈的无向图。树具有以下性质：\n1. \\(|E| = |V| - 1\\)。\n2. 任意两点之间有且只有一条简单链。\n3. 去掉任意一条边，图变为不连通（最小连通图）。\n4. 添加任意一条新边，恰好产生一个圈（极大无圈图）。" },
        { id: "spanning_tree", label: "生成树", explanation: "若图 \\(G\\) 的支撑子图是一棵树，则称其为 \\(G\\) 的生成树（或支撑树）。每个连通图至少有一棵生成树。" },
        { id: "mst_kruskal", label: "Kruskal 算法", explanation: "按边权从小到大依次尝试加入，若加入后不形成圈则保留，否则跳过。使用并查集检测圈。\n\n步骤：\n1. 将所有边按权值升序排序。\n2. 初始化并查集，每个顶点独立。\n3. 遍历边 \\((u,v,w)\\)：\n   - 若 \\(u\\) 和 \\(v\\) 不在同一集合，则合并集合，将该边加入生成树。\n   - 否则跳过。\n4. 重复直到树有 \\(|V|-1\\) 条边。\n时间复杂度 \\(O(|E|\\log|E|)\\)，适合稀疏图。" },
        { id: "mst_prim", label: "Prim 算法", explanation: "从一个顶点出发，每次选择与当前树相连的最小权边，将新顶点加入树。使用优先队列优化。\n\n步骤：\n1. 任选起点 \\(s\\)，初始化 \\(dist[s]=0\\)，其余 \\(dist[v]=\\infty\\)，\\(inTree\\) 全 false。\n2. 重复 \\(|V|\\) 次：\n   - 选取未加入树且 \\(dist\\) 最小的顶点 \\(u\\) 加入树。\n   - 对于 \\(u\\) 的每个邻接点 \\(v\\)，若 \\(w(u,v) < dist[v]\\)，更新 \\(dist[v]=w(u,v)\\)。\n3. 所有顶点加入后得到最小生成树。\n时间复杂度 \\(O(|E|\\log|V|)\\)，适合稠密图。" },
        { id: "mst_broken", label: "破圈法", explanation: "逆向贪心：从原图出发，重复删除任意圈上的最大权边，直到图中无圈。最终剩下的连通无圈图即为最小生成树。适用于手工计算，编程效率较低。" },
        { id: "sp_lp_model", label: "最短路径的线性规划模型", explanation: "给定有向图 \\(G=(V,E)\\)，边权 \\(w_{ij}\\)，起点 \\(s\\)，终点 \\(t\\)。变量 \\(x_{ij}\\in\\{0,1\\}\\) 表示边是否在路径上。模型为：\n\\[ \\min \\sum_{(i,j)\\in E} w_{ij} x_{ij} \\]\n\\[ \\text{s.t. } \\begin{cases} \\sum_{j} x_{sj} - \\sum_{i} x_{is} = 1, \\\\ \\sum_{j} x_{tj} - \\sum_{i} x_{it} = -1, \\\\ \\sum_{j} x_{vj} - \\sum_{i} x_{iv} = 0, & \\forall v \\neq s,t, \\\\ x_{ij} \\ge 0. \\end{cases} \\] \n该模型是单源单汇的单位流问题，可视为运输问题特例。" },
        { id: "dijkstra", label: "Dijkstra 算法", explanation: "适用条件：所有边权非负。\n\n核心原理：贪心 + 松弛，每次从未确定最短距离的顶点中选取当前距离最小的顶点，其距离即为最终最短距离。\n\n步骤：\n1. 初始化 \\(dist[s]=0\\)，其余 \\(dist[v]=\\infty\\)，\\(S=\\emptyset\\)。\n2. 重复 \\(|V|\\) 次：\n   - 从 \\(V\\setminus S\\) 中选取 \\(dist[u]\\) 最小的 \\(u\\) 加入 \\(S\\)。\n   - 对于 \\(u\\) 的每个出边 \\((u,v)\\)，若 \\(dist[u]+w(u,v) < dist[v]\\)，更新 \\(dist[v]\\)。\n3. \\(dist[t]\\) 即为最短路径长度。\n\n使用优先队列优化复杂度 \\(O(|E|\\log|V|)\\)。" },
        { id: "dijkstra_labeling", label: "Dijkstra 标号法（手工）", explanation: "使用两种标号：\n- P标号（永久标号）：从起点到该点的最短距离。\n- T标号（临时标号）：当前估计距离。\n\n步骤：\n1. 起点 \\(s\\) 标 P=0，其余点 T=\\(\\infty\\)。\n2. 对于新产生的P标点 \\(v_i\\)，考虑所有弧 \\((v_i,v_j)\\)：\n   - 若 \\(v_j\\) 是P标点，不修改。\n   - 若 \\(v_j\\) 是T标点，则 \\(T(v_j)=\\min(T(v_j), P(v_i)+w_{ij})\\)。\n3. 从所有T标点中选出最小值，将其改为P标点。\n4. 重复直到 \\(t\\) 获得P标号。" },
        { id: "bellman_ford", label: "Bellman-Ford 算法", explanation: "适用条件：可处理负权边，能检测负权环。\n\n步骤：\n1. 初始化 \\(dist[s]=0\\)，其余 \\(dist[v]=\\infty\\)。\n2. 重复 \\(|V|-1\\) 次：\n   - 遍历每条边 \\((u,v)\\)，若 \\(dist[u]+w(u,v) < dist[v]\\)，则更新 \\(dist[v]\\)。\n3. 再遍历一次所有边：若仍有可更新的边，则图中存在负权环。\n\n时间复杂度 \\(O(|V||E|)\\)。" },
        { id: "floyd", label: "Floyd-Warshall 算法", explanation: "目的：求所有点对之间的最短路径。\n\n动态规划思想：设 \\(d^{(k)}[i][j]\\) 为只允许经过前 \\(k\\) 个顶点时 \\(i\\to j\\) 的最短路径长度。递推式：\n\\[ d^{(k)}[i][j] = \\min\\left(d^{(k-1)}[i][j],\\ d^{(k-1)}[i][k] + d^{(k-1)}[k][j]\\right) \\]\n\n步骤：\n1. 初始化 \\(dist[i][j] = w_{ij}\\)（若无边则为 \\(\\infty\\)），\\(dist[i][i]=0\\)。\n2. 对 \\(k=1\\dots n\\)：\n   - 对 \\(i=1\\dots n\\)，\\(j=1\\dots n\\)：\n     - \\(dist[i][j] = \\min(dist[i][j], dist[i][k]+dist[k][j])\\)\n3. 若 \\(dist[i][i] < 0\\) 则存在负环。\n\n时间复杂度 \\(O(|V|^3)\\)。" },
        { id: "sp_dual", label: "最短路径的对偶问题", explanation: "最短路径问题的对偶模型可以推导出Bellman-Ford等算法的理论基础。对偶变量 \\(\\pi_v\\) 可视为势函数，对偶约束为 \\(\\pi_j - \\pi_i \\le w_{ij}\\)，目标为最大化 \\(\\pi_t - \\pi_s\\)。这对应于最长路径问题。" },
        { id: "network_def", label: "网络的定义", explanation: "网络是一类特殊的有向图 \\(G=(V,E)\\)，每条边 \\((i,j)\\) 有一个非负容量 \\(c_{ij}\\)，并指定源点 \\(s\\) 和汇点 \\(t\\)。网络中的流 \\(f_{ij}\\) 满足：\n- 容量约束：\\(0 \\le f_{ij} \\le c_{ij}\\)。\n- 流量平衡：对任意中间顶点 \\(v \\neq s,t\\)，流入量等于流出量。\n- 净流量：源点的净流出量（或汇点的净流入量）称为流的流量 \\(|f|\\)。" },
        { id: "maxflow_lp_model", label: "最大流的线性规划模型", explanation: "最大流问题可以写成线性规划形式：\n\\[ \\max v \\]\n\\[ \\text{s.t. } \\begin{cases} \\sum_{j: (s,j)\\in E} f_{sj} - \\sum_{i: (i,s)\\in E} f_{is} = v, \\\\ \\sum_{j: (t,j)\\in E} f_{tj} - \\sum_{i: (i,t)\\in E} f_{it} = -v, \\\\ \\sum_{j: (u,j)\\in E} f_{uj} - \\sum_{i: (i,u)\\in E} f_{iu} = 0, & \\forall u \\neq s,t, \\\\ 0 \\le f_{ij} \\le c_{ij}, & \\forall (i,j)\\in E. \\end{cases} \\]\n其对偶问题即为最小割问题。" },
        { id: "cut_def", label: "割 (s-t cut)", explanation: "一个 \\(s\\)-\\(t\\) 割是将顶点集 \\(V\\) 划分成两个子集 \\(S\\) 和 \\(T\\)，满足 \\(s \\in S\\)，\\(t \\in T\\)，且 \\(S \\cap T = \\emptyset\\)，\\(S \\cup T = V\\)。割的容量为 \\(c(S,T) = \\sum_{u\\in S, v\\in T} c_{uv}\\)（只计算从 \\(S\\) 到 \\(T\\) 的边）。\n\n最小割：所有割中容量最小的割。" },
        { id: "maxflow_mincut_theorem", label: "最大流最小割定理", explanation: "在任何网络中，最大可行流的流量等于最小割的容量。\n\n证明概要：\n- 弱对偶性：任何可行流的流量不超过任何割的容量，故最大流 ≤ 最小割。\n- 强对偶性：Ford-Fulkerson算法终止时，当前流等于某个割的容量，且该割为最小割，从而等号成立。" },
        { id: "ff_algorithm", label: "Ford-Fulkerson 算法思想", explanation: "在残量网络中不断寻找增广路，直到不存在从 \\(s\\) 到 \\(t\\) 的路径为止。\n\n残量网络：对于每条边 \\((u,v)\\)，定义剩余容量 \\(r_{uv}=c_{uv}-f_{uv}\\)，同时添加反向边 \\((v,u)\\) 容量为 \\(f_{uv}\\)。\n\n增广路：残量网络中从 \\(s\\) 到 \\(t\\) 的路径，路径上的最小剩余容量称为可增量。\n\n算法步骤：\n1. 初始化 \\(f=0\\)。\n2. 在残量网络中寻找一条 \\(s\\to t\\) 的路径（BFS/DFS）。\n3. 若不存在，停止，当前流为最大流。\n4. 若存在，计算路径上最小剩余容量 \\(\\delta\\)，并更新：正向边 \\(+\\delta\\)，反向边 \\(-\\delta\\)。返回2。\n\n时间复杂度依赖于路径选择，Edmonds-Karp（BFS）为 \\(O(|V||E|^2)\\)。" },
        { id: "ff_labeling", label: "Ford-Fulkerson 标号法（手工步骤）", explanation: "标号法用于手工寻找增广路：\n\nstep 0：给源点 \\(s\\) 标号 \\((\\infty, +\\infty)\\)。\n\nstep 1：列出与已标号点相邻的未标号节点 \\(v_j\\)：\n- 若弧 \\((i,j)\\) 是正向弧且 \\(f_{ij} < c_{ij}\\)，则给 \\(j\\) 标号 \\((i, \\delta_j)\\)，其中 \\(\\delta_j = \\min(\\delta_i, c_{ij}-f_{ij})\\)。\n- 若弧 \\((j,i)\\) 是反向弧且 \\(f_{ji} > 0\\)，则给 \\(j\\) 标号 \\((-i, \\delta_j)\\)，其中 \\(\\delta_j = \\min(\\delta_i, f_{ji})\\)。\n\n若 \\(j\\) 有多个相邻标号点，取 \\(\\delta_j\\) 的最大值。\n\nstep 2：若汇点 \\(t\\) 得到标号，则从 \\(t\\) 反向追踪到 \\(s\\) 获得增广链，增量为 \\(\\delta_t\\)。按标号修改流量：正向弧加 \\(\\delta\\)，反向弧减 \\(\\delta\\)。清空标号，返回 step 1。\n\nstep 3：若 \\(t\\) 无法标号，则当前流为最大流。此时已标号点集 \\(S\\) 和未标号点集 \\(T\\) 构成最小割。" },
        { id: "mincost_flow_lp", label: "最小费用流的线性规划模型", explanation: "给定网络 \\(G=(V,E)\\)，每条边有容量 \\(c_{ij}\\) 和单位费用 \\(d_{ij}\\)，要求输送指定流量 \\(v\\)（或最大流），使得总费用最小。模型为：\n\\[ \\min \\sum_{(i,j)\\in E} d_{ij} f_{ij} \\]\n\\[ \\text{s.t. } \\begin{cases} \\sum_{j} f_{sj} - \\sum_{i} f_{is} = v, \\\\ \\sum_{j} f_{tj} - \\sum_{i} f_{it} = -v, \\\\ \\sum_{j} f_{uj} - \\sum_{i} f_{iu} = 0, & \\forall u \\neq s,t, \\\\ 0 \\le f_{ij} \\le c_{ij}, & \\forall (i,j)\\in E. \\end{cases} \\]" },
        { id: "ssp_algorithm", label: "SSP 算法（最小费用流）", explanation: "Successive Shortest Path：每次在残量网络上寻找从 \\(s\\) 到 \\(t\\) 的最短路径（按费用），并在该路径上增广尽可能大的流量。\n\n残量网络费用规则：\n- 若 \\(f_{ij} < c_{ij}\\)，则存在正向边，费用为 \\(d_{ij}\\)。\n- 若 \\(f_{ij} > 0\\)，则存在反向边，费用为 \\(-d_{ij}\\)。\n\n算法步骤：\n1. 初始化 \\(f=0\\)，总费用=0。\n2. 在残量网络上用最短路径算法（Dijkstra或Bellman-Ford）求 \\(s\\to t\\) 的最短路，得到路径 \\(p\\) 和距离 \\(dist[t]\\)。\n3. 若不存在路径或已达到需求流量，停止。\n4. 计算路径上的最大可增流量 \\(\\delta = \\min\\{ \\text{剩余需求},\\ \\min_{(u,v)\\in p} (c_{uv}-f_{uv})\\}\\)。\n5. 沿路径增广：\\(f_{uv} \\leftarrow f_{uv}+\\delta\\)，\\(f_{vu} \\leftarrow f_{vu}-\\delta\\)，总费用 \\(+ \\delta \\times dist[t]\\)。\n6. 返回步骤2。" },
        { id: "residual_network", label: "剩余网络构造", explanation: "给定原网络 \\(G\\) 和当前流 \\(f\\)，残量网络 \\(G_f\\) 的边构造规则：\n- 正向弧：若 \\(f_{ij} < c_{ij}\\)，则添加边 \\((i,j)\\)，容量为 \\(c_{ij} - f_{ij}\\)，费用为 \\(d_{ij}\\)。\n- 反向弧：若 \\(f_{ij} > 0\\)，则添加边 \\((j,i)\\)，容量为 \\(f_{ij}\\)，费用为 \\(-d_{ij}\\)（用于撤销流量）。\n零流弧只保持正向；饱和弧只保留反向。" }
    ],
    edges: [
        { from: "root_graph", to: "graph_def" },
        { from: "root_graph", to: "graph_types" },
        { from: "root_graph", to: "vertex_degree" },
        { from: "root_graph", to: "handshaking_lemma" },
        { from: "root_graph", to: "chain" },
        { from: "root_graph", to: "cycle" },
        { from: "root_graph", to: "circuit" },
        { from: "root_graph", to: "connectivity" },
        { from: "root_graph", to: "subgraph" },
        { from: "root_graph", to: "tree_def" },
        { from: "tree_def", to: "spanning_tree" },
        { from: "spanning_tree", to: "mst_kruskal" },
        { from: "spanning_tree", to: "mst_prim" },
        { from: "spanning_tree", to: "mst_broken" },
        { from: "root_graph", to: "sp_lp_model" },
        { from: "sp_lp_model", to: "dijkstra" },
        { from: "dijkstra", to: "dijkstra_labeling" },
        { from: "sp_lp_model", to: "bellman_ford" },
        { from: "sp_lp_model", to: "floyd" },
        { from: "sp_lp_model", to: "sp_dual" },
        { from: "root_graph", to: "network_def" },
        { from: "network_def", to: "maxflow_lp_model" },
        { from: "maxflow_lp_model", to: "cut_def" },
        { from: "cut_def", to: "maxflow_mincut_theorem" },
        { from: "maxflow_mincut_theorem", to: "ff_algorithm" },
        { from: "ff_algorithm", to: "ff_labeling" },
        { from: "root_graph", to: "mincost_flow_lp" },
        { from: "mincost_flow_lp", to: "ssp_algorithm" },
        { from: "mincost_flow_lp", to: "residual_network" }
    ]
};

// ===================== 动态规划 =====================
const dynamicProgrammingData = {
    nodes: [
        { id: "root_dp", label: "📊 动态规划", explanation: "动态规划是解决多阶段决策过程最优化的一种方法。通过将问题分解为相互联系的阶段，利用状态转移和最优性原理，避免重复计算，高效求解最优化问题。适用于具有最优子结构和重叠子问题的场景。" },
        { id: "dp_multistage", label: "多阶段决策问题", explanation: "实际决策问题往往包含多个阶段，每个阶段都需要做出决策，且当前阶段的决策会影响后续阶段的状态与可行策略。目标是使整个过程的总成本（或总收益）最优。动态规划专门求解此类问题。" },
        { id: "dp_concepts", label: "基本概念" },
        { id: "dp_stage", label: "阶段 (k)", explanation: "将问题按时间或空间顺序分解为若干个相互联系的阶段，通常按次序编号。" },
        { id: "dp_state", label: "状态 (S_k)", explanation: "每个阶段开始时所处的自然状况，是决策的依据。状态应包含足够的信息，能描述该阶段对后续决策的影响。" },
        { id: "dp_decision", label: "决策 (X_k)", explanation: "在每个阶段，从允许的决策集合中选择一个行动，该行动会决定下一阶段的状态。记作 \\(X_k \\in D_k(S_k)\\)。" },
        { id: "dp_policy", label: "策略", explanation: "各阶段决策的序列，即 \\(\\{X_1, X_2, \\ldots, X_n\\}\\)。一个完整的策略从初始状态出发，经过所有阶段到达终止状态。" },
        { id: "dp_transition", label: "状态转移方程", explanation: "描述当前状态与决策如何确定下一状态的函数关系：\\( S_{k+1} = T_k(S_k, X_k) \\)。" },
        { id: "dp_stage_index", label: "阶段指标函数", explanation: "记作 \\( V_k(S_k, X_k) \\)，表示在第 \\(k\\) 阶段、状态为 \\(S_k\\) 时采取决策 \\(X_k\\) 所产生的直接收益或成本。" },
        { id: "dp_process_index", label: "过程指标函数", explanation: "从第 \\(k\\) 阶段状态 \\(S_k\\) 出发，采取后续策略所获得的总收益或总成本。通常可加，即 \\( \\sum_{i=k}^n V_i \\)；也可为乘性。" },
        { id: "dp_optimal_value", label: "最优值函数", explanation: "记作 \\( f_k(S_k) \\)，表示从第 \\(k\\) 阶段状态 \\(S_k\\) 出发，采用最优策略所能达到的最优过程指标值（最小成本或最大收益）。" },
        { id: "dp_bellman_eq", label: "贝尔曼方程", explanation: "动态规划的核心递推关系：\n\\[ f_k(S_k) = \\min_{X_k \\in D_k(S_k)} \\left\\{ V_k(S_k, X_k) + f_{k+1}(S_{k+1}) \\right\\} \\]\n其中 \\( S_{k+1} = T_k(S_k, X_k) \\)，且边界条件 \\( f_{n+1}(S_{n+1}) = 0 \\)（或给定值）。该方程体现了“最优策略的子策略也是最优的”。" },
        { id: "dp_principles", label: "动态规划原理" },
        { id: "dp_optimality", label: "最优化原理 (贝尔曼原理)", explanation: "一个最优策略具有这样的性质：无论过去的状态和决策如何，对前面决策所形成的当前状态而言，余下的决策必须构成最优策略。即最优策略的子策略总是最优的。这是动态规划正确性的理论基础。" },
        { id: "dp_markov", label: "无后效性原理 (马尔可夫性)", explanation: "当前状态之后的过程只与当前状态有关，不受之前决策的影响。也就是说，状态变量必须包含足够的信息，使得后续决策只需基于当前状态即可。具有此性质的问题才能用动态规划求解。" },
        { id: "dp_substructure", label: "最优子结构", explanation: "如果一个问题的最优解包含其子问题的最优解，则称该问题具有最优子结构。动态规划要求该性质成立。" },
        { id: "dp_overlap", label: "重叠子问题", explanation: "递归求解时，不同的子问题会反复出现。动态规划通过存储子问题的解来避免重复计算，从而提高效率。" },
        { id: "dp_curse", label: "维数诅咒", explanation: "当状态变量的维数增加时，状态空间大小呈指数增长，导致计算量和存储需求急剧上升。这是动态规划的主要局限性，需要借助近似方法或降维技术。" },
        { id: "dp_solution", label: "求解方法" },
        { id: "dp_backward", label: "逆序递推法 (后向前)", explanation: "从最后一个阶段开始，逐步向前递推。适用于初始状态给定、终止状态自由的情形。步骤：\n1. 确定边界条件 \\( f_{n+1}(S_{n+1}) \\).\n2. 对 \\(k = n, n-1, \\dots, 1\\)，利用贝尔曼方程计算 \\( f_k(S_k) \\).\n3. 最终 \\( f_1(S_1) \\) 即为最优值，再反向追踪得到最优策略。" },
        { id: "dp_forward", label: "顺序递推法 (前向后)", explanation: "从第一阶段开始，逐步向后递推。适用于终止状态给定、初始状态自由的情形。状态转移方程可写为 \\( S_{k} = T_k'(S_{k-1}, X_{k-1}) \\)，递推式为 \\( f_k(S_k) = \\min_{X_{k-1}} \\{ V_{k-1}(S_{k-1}, X_{k-1}) + f_{k-1}(S_{k-1}) \\} \\)，边界条件 \\( f_1(S_1) \\) 给定。最终得到 \\( f_n(S_n) \\) 为最优值。" }
    ],
    edges: [
        { from: "root_dp", to: "dp_multistage" },
        { from: "root_dp", to: "dp_concepts" },
        { from: "dp_concepts", to: "dp_stage" },
        { from: "dp_concepts", to: "dp_state" },
        { from: "dp_concepts", to: "dp_decision" },
        { from: "dp_concepts", to: "dp_policy" },
        { from: "dp_concepts", to: "dp_transition" },
        { from: "dp_concepts", to: "dp_stage_index" },
        { from: "dp_concepts", to: "dp_process_index" },
        { from: "dp_concepts", to: "dp_optimal_value" },
        { from: "dp_concepts", to: "dp_bellman_eq" },
        { from: "root_dp", to: "dp_principles" },
        { from: "dp_principles", to: "dp_optimality" },
        { from: "dp_principles", to: "dp_markov" },
        { from: "dp_principles", to: "dp_substructure" },
        { from: "dp_principles", to: "dp_overlap" },
        { from: "dp_principles", to: "dp_curse" },
        { from: "root_dp", to: "dp_solution" },
        { from: "dp_solution", to: "dp_backward" },
        { from: "dp_solution", to: "dp_forward" }
    ]
};

// ===================== 决策论 =====================
const decisionTheoryData = {
    nodes: [
        { id: "root_decision", label: "🎲 决策论" },
        { id: "dt_uncertainty", label: "不确定性决策", explanation: "自然状态发生的概率未知，仅知道各方案在各状态下的收益（或损失）。常用五种准则进行方案选择。" },
        { id: "dt_pessimistic", label: "悲观法 (最大最小准则)", explanation: "假设每个方案必然发生其最差的结果，从中选择最差结果中最好的方案。即：\\( \\max_i \\min_j a_{ij} \\)。保守型决策者常用。" },
        { id: "dt_optimistic", label: "乐观法 (最大最大准则)", explanation: "假设每个方案必然发生其最好的结果，从中选择最好的方案。即：\\( \\max_i \\max_j a_{ij} \\)。冒险型决策者常用。" },
        { id: "dt_compromise", label: "折中准则 (赫威兹准则)", explanation: "引入乐观系数 \\( \\alpha \\in [0,1] \\)，综合最好和最差结果：\\( H_i = \\alpha \\max_j a_{ij} + (1-\\alpha) \\min_j a_{ij} \\)，选择 \\( \\max_i H_i \\)。\\( \\alpha = 1 \\) 时为乐观法，\\( \\alpha = 0 \\) 时为悲观法。" },
        { id: "dt_equal_prob", label: "等可能准则 (拉普拉斯准则)", explanation: "假设各自然状态等概率发生，计算每个方案的期望收益，取最大者。即：\\( \\max_i \\frac{1}{n} \\sum_{j=1}^n a_{ij} \\)。" },
        { id: "dt_regret", label: "最小机会损失准则 (最小遗憾准则)", explanation: "构造后悔值矩阵 \\( r_{ij} = \\max_k a_{kj} - a_{ij} \\)（同一状态下的最大收益减去当前收益），然后取每个方案的最大遗憾值，选择遗憾值最小的方案：\\( \\min_i \\max_j r_{ij} \\)。" },
        { id: "dt_risk", label: "风险性决策", explanation: "自然状态发生的概率已知，但决策结果仍具有随机性。常用准则如下。" },
        { id: "dt_max_prob", label: "最大可能准则", explanation: "选择概率最大的自然状态，然后在这一状态下选收益最大的方案。即：先找出 \\( j^* = \\arg\\max_j P(N_j) \\)，再选 \\( \\max_i a_{i j^*} \\)。忽略其他状态。" },
        { id: "dt_max_exp", label: "最大期望收益准则", explanation: "计算每个方案的期望收益 \\( E(S_i) = \\sum_j P(N_j) a_{ij} \\)，选择期望收益最大的方案。是最常用的准则。" },
        { id: "dt_min_exp_regret", label: "最小期望机会损失准则", explanation: "计算每个方案的期望遗憾 \\( E(R_i) = \\sum_j P(N_j) \\cdot (\\max_k a_{kj} - a_{ij}) \\)，选择期望遗憾最小的方案。与最大期望收益等价。" },
        { id: "dt_evpi", label: "完全信息期望值 (EVPI)", explanation: "EVPI = 完全信息下的期望收益 - 无信息时的最大期望收益。它表示通过获取完全信息（即确切知道自然状态）所能带来的期望收益增加值，也是情报价值的上限。计算公式：\\( EVPI = \\sum_j P(N_j) \\max_i a_{ij} - \\max_i E(S_i) \\)。" },
        { id: "dt_posterior", label: "后验决策 (贝叶斯决策)", explanation: "当先验概率不准确时，通过试验或调查获取新信息，利用贝叶斯公式更新概率得到后验概率，再基于后验概率做出决策。能提高决策质量。后验概率：\\( P(N_j | E) = \\frac{P(E | N_j) P(N_j)}{\\sum_k P(E | N_k) P(N_k)} \\)。" },
        { id: "dt_tree", label: "决策树", explanation: "一种直观的图形工具，用于表示多阶段决策问题。包含三种节点：决策节点（□）、状态节点（○）、结果节点（△）。分支依次为方案分支、概率分支、末端收益值。" },
        { id: "dt_tree_nodes", label: "决策树节点", explanation: "- 决策节点（□）：表示决策者在此处需要选择一个方案。\n- 状态节点（○）：表示自然状态的发生，分支概率已知。\n- 结果节点（△）：表示最终收益或成本。" },
        { id: "dt_rollback", label: "决策树逆向归纳 (Rollback)", explanation: "从末端结果节点开始，向根节点逐层计算期望值：在状态节点处计算各分支期望的加权平均，在决策节点处选择最优分支。最终得到最优决策和期望收益。" },
        { id: "dt_utility", label: "效用函数", explanation: "用来量化决策者对风险和收益的主观偏好。将货币收益转换为效用值，从而在期望效用最大化的框架下决策，可以反映风险态度。" },
        { id: "dt_risk_attitude", label: "风险态度", explanation: "根据效用函数的二阶导数判断：\n- 风险厌恶：\\( U''(x) < 0 \\)（凹函数），偏好确定性等价，有 \\( U(E[X]) \\ge E[U(X)] \\)（Jensen不等式）。\n- 风险中性：\\( U''(x) = 0 \\)（线性函数），只关心期望值。\n- 风险寻求：\\( U''(x) > 0 \\)（凸函数），偏好不确定性。" },
        { id: "dt_certainty_equiv", label: "确定性等价 (CE)", explanation: "对于一项随机收益 \\(X\\)，确定性等价是指决策者认为与接受该随机收益无差异的确定数额。即 \\(U(CE) = E[U(X)]\\)。风险厌恶时 \\(CE < E[X]\\)，风险溢价 \\( = E[X] - CE\\)。" },
        { id: "dt_risk_premium", label: "风险溢价", explanation: "风险溢价 = 期望收益 - 确定性等价。它度量了决策者为规避风险而愿意放弃的收益额。风险厌恶程度越高，风险溢价越大。" },
        { id: "dt_risk_coefficient", label: "风险厌恶系数", explanation: "度量风险厌恶的程度：\n- 绝对风险厌恶系数 (ARA)：\\( A(x) = -\\frac{U''(x)}{U'(x)} \\)。常数绝对风险厌恶 (CARA) 对应指数效用。\n- 相对风险厌恶系数 (RRA)：\\( R(x) = -x \\frac{U''(x)}{U'(x)} \\)。常数相对风险厌恶 (CRRA) 对应幂效用。" },
        { id: "dt_utility_functions", label: "常用效用函数", explanation: "- 指数效用 (CARA)：\\( u(x) = 1 - e^{-\\alpha x}, \\alpha > 0 \\)，绝对风险厌恶为常数 \\(\\alpha\\)。\n- 幂效用 (CRRA)：\\( u(x) = \\frac{x^{1-\\gamma}}{1-\\gamma} \\)（\\(\\gamma \\neq 1\\)），相对风险厌恶为常数 \\(\\gamma\\)。\n- 二次效用：\\( u(x) = x - b x^2 \\)，但仅适用于 \\(x \\le 1/(2b)\\)，具有递增绝对风险厌恶。" }
    ],
    edges: [
        { from: "root_decision", to: "dt_uncertainty" },
        { from: "dt_uncertainty", to: "dt_pessimistic" },
        { from: "dt_uncertainty", to: "dt_optimistic" },
        { from: "dt_uncertainty", to: "dt_compromise" },
        { from: "dt_uncertainty", to: "dt_equal_prob" },
        { from: "dt_uncertainty", to: "dt_regret" },
        { from: "root_decision", to: "dt_risk" },
        { from: "dt_risk", to: "dt_max_prob" },
        { from: "dt_risk", to: "dt_max_exp" },
        { from: "dt_risk", to: "dt_min_exp_regret" },
        { from: "dt_risk", to: "dt_evpi" },
        { from: "dt_risk", to: "dt_posterior" },
        { from: "root_decision", to: "dt_tree" },
        { from: "dt_tree", to: "dt_tree_nodes" },
        { from: "dt_tree", to: "dt_rollback" },
        { from: "root_decision", to: "dt_utility" },
        { from: "dt_utility", to: "dt_risk_attitude" },
        { from: "dt_utility", to: "dt_certainty_equiv" },
        { from: "dt_utility", to: "dt_risk_premium" },
        { from: "dt_utility", to: "dt_risk_coefficient" },
        { from: "dt_utility", to: "dt_utility_functions" }
    ]
};

// ===================== 博弈论 =====================
const gameTheoryData = {
    nodes: [
        { id: "root_game", label: "🎯 博弈论" },
        { id: "gt_static", label: "完全信息静态博弈", explanation: "所有参与者同时选择行动，且每个参与者对其他参与者的支付函数和策略空间有完全了解。" },
        { id: "gt_dominant_strategy", label: "占优策略", explanation: "若参与人 i 的某个策略 \\( S_i^* \\) 严格优于其所有其他策略，即对任意其他参与人的策略组合 \\( S_{-i} \\)，有 \\( u_i(S_i^*, S_{-i}) > u_i(S_i', S_{-i}) \\) 对所有 \\( S_i' \\neq S_i^* \\) 成立，则称 \\( S_i^* \\) 为严格占优策略。" },
        { id: "gt_dominant_eq", label: "占优策略均衡", explanation: "若每个参与人都存在占优策略，则这些策略的组合构成占优策略均衡。占优策略若存在则唯一，但未必存在。" },
        { id: "gt_strictly_dominated", label: "严格劣策略", explanation: "若存在另一策略 \\( S_i' \\) 使得对任意其他参与人的策略组合 \\( S_{-i} \\)，有 \\( u_i(S_i', S_{-i}) > u_i(S_i, S_{-i}) \\)，则称 \\( S_i \\) 为严格劣策略。理性参与者不会选择严格劣策略。" },
        { id: "gt_ieds", label: "重复剔除严格劣策略", explanation: "通过反复剔除每个参与人策略集中的严格劣策略，若最后只剩下唯一的策略组合，则称为重复剔除严格劣策略后的均衡。" },
        { id: "gt_nesh_eq_pure", label: "纯策略纳什均衡", explanation: "在策略式博弈 \\( G = \\{S_1, \\dots, S_n; u_1, \\dots, u_n\\} \\) 中，策略组合 \\( (S_1^*, \\dots, S_n^*) \\) 是一个纳什均衡，若对每个参与人 i，有 \\( u_i(S_i^*, S_{-i}^*) \\ge u_i(S_i, S_{-i}^*) \\) 对所有 \\( S_i \\in S_i \\) 成立。即无人能通过单方面改变策略获得更高收益。" },
        { id: "gt_finite_nash", label: "有限策略纳什均衡求解（划线法）", explanation: "对于有限策略博弈，可以通过划线法找出纯策略纳什均衡：对每个参与人，在给定对手策略下找出其收益最大的策略，并在对应收益下划线；所有划线格对应的策略组合即为纯策略纳什均衡。" },
        { id: "gt_continuous_nash", label: "无限连续策略纳什均衡求解", explanation: "当策略空间是连续区间时，可利用一阶条件 \\( \\frac{\\partial u_i}{\\partial s_i} = 0 \\) 导出各参与人的反应函数 \\( R_i(s_{-i}) \\)，然后联立反应函数方程组求解纳什均衡。" },
        { id: "gt_mixed_strategy", label: "混合策略", explanation: "在 \\( G = \\{S_1, \\dots, S_n; u_1, \\dots, u_n\\} \\) 中，设参与人 i 有 k 个纯策略，则称概率分布 \\( \\sigma_i = (\\sigma_{i1}, \\dots, \\sigma_{ik}) \\) 为 i 的一个混合策略，其中 \\( \\sigma_{ij} \\) 是参与人 i 选择纯策略 \\( s_j \\) 的概率。" },
        { id: "gt_mixed_nash", label: "混合策略纳什均衡", explanation: "混合策略组合 \\( \\sigma^* \\) 是一个混合策略纳什均衡，如果对每个参与人 i 及其任意混合策略 \\( \\sigma_i \\)，有 \\( E_i(\\sigma_i^*, \\sigma_{-i}^*) \\ge E_i(\\sigma_i, \\sigma_{-i}^*) \\)。即在给定他人混合策略下，无人能通过改变自己的混合策略获得更高期望收益。" },
        { id: "gt_mixed_solve_max", label: "混合策略求解：效用值最大化法", explanation: "给定其他参与人的混合策略，参与人 i 的期望效用函数 \\( E_i \\)。对 \\( E_i \\) 关于其混合策略变量求偏导，令所有偏导等于零（且概率和为一），解方程组得到混合策略纳什均衡。" },
        { id: "gt_mixed_solve_equal", label: "混合策略求解：效用值等价法", explanation: "在混合策略纳什均衡中，若参与人 i 的混合策略对多个纯策略赋予正概率，则这些纯策略在他人均衡混合策略下的期望收益必须相等。据此可列出方程求解。" },
        { id: "gt_zero_sum", label: "零和博弈（矩阵博弈）", explanation: "二人零和博弈中，一方的收益等于另一方的损失。博弈可表示为 \\( G = \\{S_1, S_2, A\\} \\)，其中 \\( A = (a_{ij}) \\) 是参与人1的收益矩阵，参与人2的收益为 \\( -a_{ij} \\)。" },
        { id: "gt_zero_sum_pure", label: "零和博弈纯策略纳什均衡的存在条件", explanation: "矩阵博弈存在纯策略纳什均衡的充要条件为：\\( \\max_i \\min_j a_{ij} = \\min_j \\max_i a_{ij} \\)。该值称为博弈的值。" },
        { id: "gt_dominance", label: "矩阵博弈的优超原则", explanation: "两条性质：①若矩阵 A 的某行（列）每个元素均严格大于另一行（列）的对应元素，则可划去被严格占优的行（列）。②将矩阵每个元素加上同一个常数，博弈的解不变，博弈的值加上该常数。" },
        { id: "gt_zero_sum_mixed", label: "零和博弈混合策略纳什均衡的存在性", explanation: "任何矩阵博弈都存在混合策略纳什均衡（冯·诺依曼极小化极大定理）。" },
        { id: "gt_zero_sum_lp", label: "零和博弈混合策略的线性规划求解", explanation: "对于参与人1，求解线性规划：\\[ \\max v \\quad \\text{s.t.} \\sum_{i=1}^m a_{ij} x_i \\ge v,\\ j=1..n,\\ \\sum_i x_i = 1,\\ x_i \\ge 0 \\] 其中 \\( x \\) 是参与人1的混合策略，\\( v \\) 是博弈的值。参与人2的混合策略由对偶问题给出。" },
        { id: "gt_dynamic", label: "完全信息动态博弈", explanation: "参与者依次行动，后行动者能观察到先行动者的选择（完美信息）。通常用扩展式（博弈树）表示。" },
        { id: "gt_subgame", label: "子博弈", explanation: "子博弈是原博弈的一部分，必须满足：①起点是一个单点信息集；②包含起点后的所有后续节点；③不分裂任何信息集。在完美信息动态博弈中，每个决策节点都起始一个子博弈。" },
        { id: "gt_spne", label: "子博弈精炼纳什均衡（SPNE）", explanation: "策略组合 \\( s^* \\) 是子博弈精炼纳什均衡，如果它在整个博弈和每一个子博弈上都构成纳什均衡。SPNE 剔除了不可置信的威胁。" },
        { id: "gt_sequential_discrete", label: "离散有限阶段动态博弈的求解（逆向归纳）", explanation: "从最后一个子博弈开始，求解该子博弈的纳什均衡，然后将均衡收益代入上一层，依次向前推进，直到初始节点。适用于有限阶段完美信息动态博弈。" },
        { id: "gt_sequential_continuous", label: "连续策略有限阶段动态博弈的求解", explanation: "写出各参与者的效用函数，利用一阶条件得到最优反应函数，然后将反应函数代入上一层的效用函数，不断向上层递推，最终得到子博弈精炼纳什均衡。" },
        { id: "gt_sequential_infinite", label: "无限阶段动态博弈的求解", explanation: "假设策略是时不变的，寻找平稳均衡。通过动态规划或条件方程求解临界反应点，通常涉及贝尔曼方程。" },
        { id: "gt_incomplete", label: "不完全信息博弈", explanation: "至少有一个参与人对其他参与人的支付函数或策略空间不完全了解。" },
        { id: "gt_harsanyi", label: "海萨尼转换", explanation: "将不完全信息博弈转化为完全但不完美信息博弈：引入“自然”作为虚拟参与人，首先以某种概率分布随机选择参与人的类型（支付函数参数）。然后各参与人知道自己的类型，但不知道他人的类型，只知道类型的先验分布。" },
        { id: "gt_bayesian_nesh", label: "贝叶斯纳什均衡", explanation: "在不完全信息静态博弈中，参与人根据各自类型选择行动，且最大化期望效用（期望是对他人类型的条件分布）。策略是类型到行动的函数。贝叶斯纳什均衡要求：给定自己的类型和其他人的策略，每个参与人选择的行动最大化自己的期望效用。" },
        { id: "gt_pbe", label: "完美贝叶斯均衡（PBE）", explanation: "用于不完全信息动态博弈的解概念。要求：①在每个信息集上，参与人根据贝叶斯法则更新对他人类型的信念；②给定信念，策略在每一个后续子博弈上构成最优反应；③信念与策略一致。" }
    ],
    edges: [
        { from: "root_game", to: "gt_static" },
        { from: "root_game", to: "gt_dynamic" },
        { from: "root_game", to: "gt_incomplete" },
        { from: "gt_static", to: "gt_dominant_strategy" },
        { from: "gt_dominant_strategy", to: "gt_dominant_eq" },
        { from: "gt_static", to: "gt_strictly_dominated" },
        { from: "gt_strictly_dominated", to: "gt_ieds" },
        { from: "gt_static", to: "gt_nesh_eq_pure" },
        { from: "gt_nesh_eq_pure", to: "gt_finite_nash" },
        { from: "gt_nesh_eq_pure", to: "gt_continuous_nash" },
        { from: "gt_static", to: "gt_mixed_strategy" },
        { from: "gt_mixed_strategy", to: "gt_mixed_nash" },
        { from: "gt_mixed_nash", to: "gt_mixed_solve_max" },
        { from: "gt_mixed_nash", to: "gt_mixed_solve_equal" },
        { from: "gt_static", to: "gt_zero_sum" },
        { from: "gt_zero_sum", to: "gt_zero_sum_pure" },
        { from: "gt_zero_sum", to: "gt_dominance" },
        { from: "gt_zero_sum", to: "gt_zero_sum_mixed" },
        { from: "gt_zero_sum_mixed", to: "gt_zero_sum_lp" },
        { from: "gt_dynamic", to: "gt_subgame" },
        { from: "gt_dynamic", to: "gt_spne" },
        { from: "gt_spne", to: "gt_sequential_discrete" },
        { from: "gt_spne", to: "gt_sequential_continuous" },
        { from: "gt_spne", to: "gt_sequential_infinite" },
        { from: "gt_incomplete", to: "gt_harsanyi" },
        { from: "gt_incomplete", to: "gt_bayesian_nesh" },
        { from: "gt_incomplete", to: "gt_pbe" }
    ]
};

// ===================== 全局映射 =====================
const chapterMap = {
    linear: { name: "线性规划与对偶理论", data: linearProgrammingData },
    transport: { name: "运输问题", data: transportProblemData },
    integer: { name: "整数规划", data: integerProgrammingData },
    nonlinear: { name: "非线性规划", data: nonlinearProgrammingData },
    network: { name: "图与网络", data: graphNetworkData },
    dynamic: { name: "动态规划", data: dynamicProgrammingData },
    decision: { name: "决策论", data: decisionTheoryData },
    game: { name: "博弈论", data: gameTheoryData }
};

const chapterOptions = [
    { value: "linear", label: "🔹 线性规划与对偶理论" },
    { value: "transport", label: "🚚 运输问题" },
    { value: "integer", label: "🧩 整数规划" },
    { value: "nonlinear", label: "📈 非线性规划" },
    { value: "network", label: "🌐 图与网络" },
    { value: "dynamic", label: "📊 动态规划" },
    { value: "decision", label: "🎲 决策论" },
    { value: "game", label: "🎯 博弈论" }
];